//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpendThriftModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDRESS_BOOK
    {
        public string CUSTOMER { get; set; }
        public int ADDRESS_BOOK_ID { get; set; }
        public string STREET_ADDRESS { get; set; }
        public int APARTMENT { get; set; }
        public string STATE { get; set; }
        public string COUNTRY { get; set; }
        public string ZIPCODE { get; set; }
    
        public virtual CUSTOMER CUSTOMER1 { get; set; }
    }
}
