//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpendThriftModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public CUSTOMER()
        {
            this.ADDRESS_BOOK = new HashSet<ADDRESS_BOOK>();
            this.Reviews = new HashSet<Review>();
            this.Carts = new HashSet<Cart>();
            this.Orders = new HashSet<Order>();
        }
    
        public string USERNAME { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public System.DateTime DOB { get; set; }
        public string EMAIL { get; set; }
        public int PHONE_NUMBER { get; set; }
        public string PASSWORD { get; set; }
    
        public virtual ICollection<ADDRESS_BOOK> ADDRESS_BOOK { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual BillingInformation BillingInformation { get; set; }
    }
}
