//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpendThriftModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedbackResponse
    {
        public int ID { get; set; }
        public int ResponseFor { get; set; }
        public string Response { get; set; }
        public Nullable<System.DateTime> RespondedOn { get; set; }
    
        public virtual Feedback Feedback { get; set; }
    }
}
