//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpendThriftModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Reviews = new HashSet<Review>();
            this.Categories = new HashSet<Category>();
            this.Carts = new HashSet<Cart>();
            this.OrderProducts = new HashSet<OrderProduct>();
        }
    
        public int Product_ID { get; set; }
        public string Name { get; set; }
        public int Quantity { get; set; }
        public int Price { get; set; }
        public Nullable<int> Status { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }
    }
}
